version: "3"
services:
  # nginx:
  #   image: nginx:stable-alpine
  #   ports:
  #     - "5000:80"
  #   networks:
  #     - mern-app
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  express_server:
    image: express_server
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 5000
    # networks:
    #   - mern-app
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
  # migration:
  #   image: express_server
  #   ports:
  #     - 5001
  #   depends_on:
  #     - mongo
  #   networks:
  #     - mern-app
  #   command: yarn seed:run
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express
    ports:
      - 8081:8081
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
